spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: optimusmac
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  level:
    org:
      springframework:
        security: DEBUG



logging:
  level:
    org:
      springframework:
        web: DEBUG

  upload-dir: ./images
image:
  upload-dir: src/main/resources/static